### PR TITLE
Fixlayout

### PR DESCRIPTION
**Pull request by kulvait**
Fix of the bug where there could be processed childrens before their parents which would lead into the error when plotting such fishplot.

### CODE REVIEW

**Comment by chrisamiller** [comment]
Sorry it's taken me so long to get to this. I'm not sure exactly what problem this solves.  Can you provide some example code that triggers incorrect behavior under the current package?

**Comment by kulvait** [comment]
Well,
lets take your example. I think you don't have to assume anything about order of clones. Therefore if you exec
```

    library(fishplot)

    #provide a list of timepoints to plot
    #You may need to add interpolated points to end up with the desired
    #visualization. Example here was actually sampled at days 0 and 150
    timepoints=c(0,30,75,150)

    #provide a matrix with the fraction of each population
    #present at each timepoint
    frac.table = matrix(
      c(100, 45, 00, 00,
         02, 00, 00, 00,
         02, 00, 02, 01,
         98, 00, 95, 40),
      ncol=length(timepoints))

    #provide a vector listing each clone's parent
    #(0 indicates no parent)
    parents = c(0,1,1,3)


   #Now just rearrange clones.
        frac.table = frac.table[c(4,3,2,1),]
        parents = c(2,4,4,0)
    #create a fish object
    fish = createFishObject(frac.table,parents,timepoints=timepoints)

    #calculate the layout of the drawing
    fish = layoutClones(fish)

    #draw the plot, using the splining method (recommended)
    #and providing both timepoints to label and a plot title
    fishPlot(fish,shape="spline",title.btm="Sample1",
             cex.title=0.5, vlines=c(0,150),
             vlab=c("day 0","day 150"))

```
Then install_github("kulvait/fishplot") woks and your code does not.
Vojtech.

**Comment by chrisamiller** [comment]
Thanks for following up - I'll take a look at this code shortly

**Comment by chrisamiller** [comment]
Really sorry that it's taken so long to get to this. Working on integrating these changes now - should have a version 0.5 out shortly that add this fix and a few other features

**Comment by chrisamiller** [comment]
Added your proposed code and some from your fork, along with a test.  Thanks for the bug report and contribution!

**Comment by kulvait** [comment]
Thank you! You have created a very good plotting tool.

Wish you a nice Christmas and Happy New Year!

Vojtech.

**Pull request closed without merging**
